language: objective-c
osx_image: xcode7

before_install:
    - gem install activesupport
    - gem install cocoapods -v 0.39.0 --no-rdoc --no-ri --no-document --quiet

script:
    - set -o pipefail
    - xcodebuild -workspace AeroGearHttp.xcworkspace -scheme AeroGearHttpTests -sdk iphonesimulator -configuration Release clean test

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master
